name: DocBox

on:
  push:
    branches:
      - master
      - main
    paths:
      - '**.cfc'
      - '.github/workflows/*.yml'

env:
  MODULE_ID: sqlFormatter
  VERSION: 

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Generate Docs
        uses: Ortus-Solutions/commandbox-action@v1.0.2
        with:
          cmd: run-script build:docs
      
      - name: Commit Docs to Repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "📖 DOC: Auto-generate API docs"
      
      - name: Setup env.VERSION
        uses: Ortus-Solutions/commandbox-action@v1.0.2
        with:
          cmd: echo "VERSION=`box package version`" >> $GITHUB_ENV

      - name: Upload API Docs to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: "apidocs.ortussolutions.com"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
          SOURCE_DIR: "docs"
          DEST_DIR: "coldbox-modules/${{ env.MODULE_ID }}/${{ env.VERSION }}"